config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  devise_for :users

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :bigint           not null, primary key
#  body       :text
#  user_id    :bigint           not null
#  post_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :body, presence: true, length: { minimum: 4, maximum: 200 }
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :bigint           not null, primary key
#  body       :text
#  title      :string
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Post < ApplicationRecord
  belongs_to :user, required: true

  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 5, maximum: 100 }
  validates :body, presence: true, length: { minimum: 10, maximum: 10_000 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  name                   :string(30)
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, length: { maximum: 30, minimum: 4 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  include ConfigureDeviseParameters
  include RedirectAfterSignIn
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: %i[ edit update destroy ]
  before_action :set_post, only: %i[ create ]
  before_action :authorize_user!, only: %i[ edit update destroy ]

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post

    if @comment.save
      redirect_to post_url(@comment.post), notice: "Comment was successfully created."
    else
      @post_presenter = PostPresenter.new(post: @post, new_comment: @comment)
      render 'posts/show'
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to post_url(@comment.post), notice: "Comment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy

    redirect_to @comment.post, notice: "Comment was successfully destroyed."
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:body, :user_id, :post_id)
  end

  def authorize_user!
    authorize @comment
  end
end

app/controllers/concerns/configure_devise_parameters.rb
module ConfigureDeviseParameters
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  end
end

app/controllers/concerns/redirect_after_sign_in.rb
module RedirectAfterSignIn
  extend ActiveSupport::Concern

  included do
    before_action :store_user_location!, if: :storable_location?

    private
    # Its important that the location is NOT stored if:
    # - The request method is not GET (non idempotent)
    # - The request is handled by a Devise controller such as Devise::SessionsController as that could cause an
    #    infinite redirect loop.
    # - The request is an Ajax request as this can lead to very unexpected behaviour.
    def storable_location?
      request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
    end

    def store_user_location!
      # :user is the scope we are authenticating
      store_location_for(:user, request.fullpath)
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[ new edit create update destroy ]
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authorize_user!, only: %i[ edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  # GET /posts/1
  def show
    @post_presenter = PostPresenter.new(post: @post, comments_page: params[:page])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to post_url(@post), notice: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: "Post was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy

    redirect_to posts_url, notice: "Post was successfully destroyed."
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:body, :title)
  end

  def authorize_user!
    authorize @post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="card" style="margin: 10px 0" data-test="comment">
  <div class="card-body">
    <h5 class="card-title"><%= comment.user.name %></h5>
    <h6 class="card-subtitle mb-2 text-muted">Posted <%= time_ago_in_words(comment.created_at) %> ago.</h6>
    <p class="card-text"><%= comment.body %></p>

    <% if policy(comment).edit? %>
       <%= link_to 'Edit', edit_post_comment_path(comment.post, comment) %> |
    <% end %>
    <% if policy(comment).destroy? %>
      <%= link_to 'Destroy', post_comment_path(comment.post, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [comment.post, comment]) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :body, 'Add your comment' %>
    <%= form.text_area :body, class: 'form-control', rows: 3 %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', post_path(@comment.post) %>

app/views/layouts/_flash_messages.html.erb
<% if notice %>
  <div class="alert alert-primary" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar fixed-top navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Posts', posts_path, { class: 'navbar-brand' } %>

    <div>
      <% if current_user %>
        <%= link_to current_user.name, edit_user_registration_path, class: "d-inline-block" %>
        <%= button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'btn btn-danger', form_class: 'd-inline-block' %>
      <% else %>
        <%=
          button_tag(
            'Sign In',
            class: 'btn btn-primary',
            form_class: 'd-inline-block',
            data: { 'bs-toggle': 'modal', 'bs-target': '#signInModal' }
          )
        %>
        <%= button_to 'Sign Up', new_user_registration_path, method: :get, class: 'btn btn-warning', form_class: 'd-inline-block' %>
      <% end %>
    </div>
  </div>
</nav>

<%= render 'devise/sessions/sign_in_modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YetAnotherPostsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container" style="margin-top: 80px;">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 10 %>
  </div>

  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div data-test="post">
  <h2><%= link_to post.title, post_path(post) %></h2>
  <span><b>Author:</b> <%= post.user.name %></span>
  <p><%= truncate(post.body, length: 250) %></p>

  <span class="text-muted">Posted <%= time_ago_in_words(post.created_at) %> ago<span>
</div>

app/views/posts/_post_spacer.html.erb
<hr/>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% if current_user %>
  <%= button_to 'New Post', new_post_path, method: :get, class: 'btn btn-primary' %>
<% end %>

<hr>

<%= render(partial: @posts, spacer_template: 'posts/post_spacer') || "No posts yet." %>

<hr/>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h2><%= @post_presenter.title %></h2>

<p>
  <strong>Author:</strong>
  <%= @post_presenter.author %>
</p>

<div>
  <%= simple_format @post_presenter.body %>
</div>

<h6 class="text-muted">Posted <%= time_ago_in_words(@post_presenter.created_at) %> ago.</h6>

<% if policy(@post_presenter.post).edit? %>
  <%= link_to 'Edit', edit_post_path(@post_presenter.post) %> |
<% end %>
<% if policy(@post_presenter.post).destroy? %>
  <%= link_to 'Destroy', @post_presenter.post, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<hr/>
<div id="comments">
  <h2>Comments</h2>
  <%= render(@post_presenter.comments) || "No comments yet." %>

  <%= paginate @post_presenter.comments, params: { anchor: 'comments' } %>
</div>
<% if current_user %>
  <hr/>
  <%= render "comments/form", comment: @post_presenter.new_comment %>
<% end %>